stages:
  - pre-flight
  - trigger

.runner: &runner
  image: ${GCP_IAC_RUNNER}
  tags:
    - Oxinus-prod
  variables:
    TERRAGRUNT_WORKING_DIR: "./${CI_ENVIRONMENT_NAME}"

not-behind-master:
  stage: pre-flight
  <<: *runner
  allow_failure: false
  # Override default before script
  before_script:
    - echo "Checking to see if branch has any commits behind master"
  # Get the number of commits this branch is ahead-of and behind master
  # We should not run terraform that is behind master, only ahead
  # So abort pipeline if behind
  script:
    - |
      if [[ $(git rev-list --left-right --count master...$(git branch --show-current) | awk -F' ' '{print $1}') -gt "0" ]]; then
        echo "Current branch ${CI_COMMIT_REF_NAME} is behind master but should only be ahead so exiting"
        exit 1;
      else
        echo "Current branch ${CI_COMMIT_REF_NAME} is up to date so ok to continue"
        exit 0;
      fi

generate-ami-list:
  <<: *runner
  stage: trigger
  script:
    - ./.scripts/list-amis.py
