version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  vote:
    image: frontend-app
    ports:
      - "5000:80"
      
  worker:
    image: worker-app
  visualizer:
    image: result-app
    ports: 
      - "50001:8080"
